# Generated by Django 2.1.1 on 2018-10-02 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Temps',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='Date')),
                ('new_york', models.FloatField(verbose_name='New York')),
                ('san_francisco', models.FloatField(verbose_name='San Francisco')),
                ('austin', models.FloatField(verbose_name='Austin')),
            ],
            options={
                'db_table': 'example_temps',
            },
        ),
    ]
