# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-12 20:07
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted_terms', models.BooleanField(default=False)),
                ('email_reg_code', models.CharField(db_index=True, max_length=25)),
                ('account_activated', models.BooleanField(default=False)),
                ('oauth_scope', models.CharField(choices=[('read write', 'Read/Write'), ('read', 'Read Only')], default='read write', max_length=255)),
                ('timezone', models.CharField(default='America/Denver', max_length=256, verbose_name='Timezone')),
                ('page_size', models.IntegerField(default=20, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Page Result Size')),
                ('api_access', models.BooleanField(default=False, verbose_name='API Access')),
                ('api_code', models.CharField(blank=True, default=None, max_length=35, null=True, verbose_name='API Auth Token')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auth_user_profile',
            },
        ),
    ]
